### PR TITLE
Revert "[TECH-77] footer upgrade"

### PR DESCRIPTION
**Pull request by maxxfreund**
Reverts Concordia-Game-Development/CGDWebsite#19

### CODE REVIEW

**Review by peach3es — CHANGES_REQUESTED** [review]
image

would suggest having, between the desktop & mobile view, the icons don't stretch to take the space as the window size changes

**Review by peach3es — CHANGES_REQUESTED** [review]
sonic-boom-knuckles

Yum code looking mighty tasty

**Review by maxxfreund — COMMENTED** [review]
requested changes made in the last commit

**Review by peach3es — APPROVED** [review]
skeleton-puppet-meme-pixel-art

merging this RN

**Pull request merged**
